# frozen_string_literal: true

module Icinga2
  module API
    # Read-only description of the Icinga2 object types this gem knows about.
    #
    # The catalog is a snapshot of the server's own /v1/types endpoint, frozen
    # into data/icinga2_types.json and regenerated by `rake types:snapshot`.
    # It is what lets the generic collection layer build endpoints, validate
    # attribute names and follow references between objects without hardcoding
    # any of it per type.
    class TypeCatalog

      SNAPSHOT_PATH = File.expand_path('../../../data/icinga2_types.json', __dir__)

      # A reference from one object type to another, as declared by Icinga2
      # through the +ref_type+ / +navigation_name+ / +array_rank+ triplet.
      class Relation

        attr_reader :field, :ref_type, :navigation_name, :array_rank

        def initialize(field, attributes)
          @field           = field
          @ref_type        = attributes['ref_type']
          @navigation_name = attributes['navigation_name']
          @array_rank      = attributes['array_rank'].to_i
          freeze
        end

        # Whether the field holds a list of references rather than a single one.
        def collection?
          array_rank.positive?
        end

      end

      # One Icinga2 object type: where to reach it, what it holds, what it
      # points to.
      class Type

        attr_reader :name, :plural_name, :endpoint, :base_chain, :fields, :relations

        def initialize(attributes)
          @name        = attributes['name']
          @plural_name = attributes['plural_name']
          @endpoint    = attributes['endpoint']
          @base_chain  = attributes.fetch('base_chain', []).freeze
          @fields      = attributes.fetch('fields', {}).freeze
          @relations   = build_relations(attributes.fetch('relations', {}))
          freeze
        end

        # The variable an Icinga2 filter uses to address objects of this type:
        # the type name lowercased and unseparated ("scheduleddowntime").
        # Getting it wrong answers 404 "No objects found" instead of an error,
        # so it is derived rather than written out.
        def filter_variable
          name.downcase
        end

        def field?(name)
          fields.key?(name.to_s)
        end

        # The Relation declared on +name+, or nil when that field references
        # nothing. Note that Icinga2 declares no reference on any service_name
        # field: those arcs are wired by hand in the resource classes.
        def relation(name)
          relations[name.to_s]
        end

        alias to_s name

        private

        def build_relations(raw)
          raw.to_h { |field, attributes| [field, Relation.new(field, attributes)] }.freeze
        end

      end

      class << self

        # The catalog shipped with the gem. Loaded once per process.
        def default
          @default ||= new(SNAPSHOT_PATH)
        end

      end

      def initialize(path = SNAPSHOT_PATH)
        @path  = path
        @types = load_types(path)
      end

      attr_reader :path

      # Icinga type names, sorted, e.g. ["Comment", "Dependency", ...].
      def names
        @types.keys.sort
      end

      def key?(name)
        @types.key?(normalize(name))
      end

      # Accepts the Icinga name ("ScheduledDowntime") or a snake_case symbol
      # (:scheduled_downtime).
      def fetch(name)
        type = normalize(name)
        @types.fetch(type) do
          raise Error::UnknownType, "unknown Icinga2 object type '#{type}' (known: #{names.join(', ')})"
        end
      end

      private

      def load_types(path)
        raw = JSON.parse(File.read(path), freeze: true)
        raw.fetch('types').transform_values { |attributes| Type.new(attributes) }.freeze
      end

      # "scheduled_downtime" and :scheduled_downtime both mean "ScheduledDowntime";
      # an already-camelized name is left untouched.
      def normalize(name)
        string = name.to_s
        return string if string.match?(/\A[A-Z]/) && !string.include?('_')

        string.split('_').map(&:capitalize).join
      end

    end
  end
end
