AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/LineLength:
  Max: 115
